# Generated by Django 4.1.2 on 2022-11-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(default="project.png", upload_to=""),
        ),
    ]
