# Generated by Django 4.1.2 on 2022-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_options_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_used",
            field=models.CharField(max_length=200),
        ),
    ]
