# Generated by Django 4.1.2 on 2022-11-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineer",
            name="tech_stack",
            field=models.CharField(
                blank=True,
                default="stack_one | stack_two | stack_three",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="engineer",
            name="years_of_experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
