# Generated by Django 4.1.2 on 2022-11-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_engineer_tech_stack_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineer",
            name="avatar",
            field=models.ImageField(default="avatar.svg", upload_to=""),
        ),
    ]
