# Generated by Django 4.1.2 on 2022-11-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_engineer_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineer",
            name="avatar",
            field=models.ImageField(default="profile.png", upload_to=""),
        ),
    ]
