# Generated by Django 4.1.2 on 2022-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_engineer_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engineer",
            name="bio",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="engineer",
            name="tech_stack",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
