# Generated by Django 4.1.2 on 2022-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inbox",
            old_name="sender",
            new_name="receiver",
        ),
        migrations.AlterField(
            model_name="inbox",
            name="body",
            field=models.CharField(max_length=500),
        ),
    ]
