# Generated by Django 4.1.2 on 2022-12-07 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mail", "0003_inbox_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="engineer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engineer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inbox",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="inbox",
            name="sender",
        ),
        migrations.AddField(
            model_name="inbox",
            name="sender",
            field=models.ManyToManyField(
                related_name="mail_sender", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
