# Generated by Django 4.1.2 on 2022-12-10 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mail", "0005_remove_inbox_receiver_remove_inbox_sender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="receiver",
        ),
        migrations.AddField(
            model_name="inbox",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
